package com.crustafrica.assessment.dto;

public enum Status {
    SUCCESS, INTERNAL_ERROR, FAILED_VALIDATION, NOT_FOUND, INVALID_SERVICE_ERROR,CONFLICT, CREATED, FORBIDDEN, NO_CONTENT, PAYMENT_REQUIRED,PRECONDITION_FAILED,UPGRADE_REQUIRED;
}
